server:
  port: 80
dubbo:
  application:
    name: web-manager
  registry:
    address: zookeeper://192.168.74.188:2181
    protocol:
      #自动查找一个可用的端口，默认为20880
      port: -1
    consumer:
      #首次启动不检查提供者是否存在
      check: false