dubbo:
  application:
    name: stu-service
  registry:
    address: zookeeper://192.168.74.188:2181
  protocol:
    #自动查找一个可用的端口，默认是20880
    port: -1
    consumer:
      #首次启动不检查提供者是否存在
      check: false
spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

